if-else-switch tasks are completed
emakhachek/js-basic pull request #6
Opened 2019-10-22 15:21 UTC by emakhachek

2019-11-06 22:32 UTC, lizarusi requested changes

2019-11-06 22:32 UTC, lizarusi commented on Exercises/if-else-switch/if-else-switch.js
> +  if (password.length != 8) {
!==

2019-11-06 22:32 UTC, lizarusi commented on Exercises/if-else-switch/if-else-switch.js
> +  console.log(codeToMissingComplexityElement[errorCode]);
you need to return here the message about missing element

2019-12-14 20:53 UTC, Mike-Savin approved these changes

2019-12-14 21:36 UTC, merged