functions tasks are completed
emakhachek/js-basic pull request #7
Opened 2019-10-30 17:14 UTC by emakhachek

2019-11-01 09:48 UTC, Mike-Savin requested changes

2019-11-01 09:48 UTC, Mike-Savin commented on Exercises/functions/functions.js
> +}
You can simplify it using `function.length` property:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

2019-11-01 09:48 UTC, Mike-Savin commented on Exercises/functions/functions.js
> +}
Rest syntax should be preferred:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters
Also you log not params, but only their length

2019-11-01 09:48 UTC, Mike-Savin commented on Exercises/functions/functions.js
> +(function () { })();
Since your function is empty nothing is encapsulated

2019-11-06 22:27 UTC, lizarusi approved these changes
one small comment, gj :)

2019-11-06 22:27 UTC, lizarusi commented on Exercises/functions/functions.js
> +  return console.log(takeMyParametersAmount.length);
take length of the function itself, to get amount of parameters it expect

2019-11-08 18:57 UTC, merged