arrays tasks are completed
emakhachek/js-basic pull request #8
Opened 2019-11-04 10:42 UTC by emakhachek

2019-11-06 22:20 UTC, lizarusi requested changes

2019-11-06 22:20 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +    let arr = Array.from({ length: parseInt(Math.random() * 100) }, () => Math.floor(Math.random() * 100));
return this array for func

2019-11-06 22:20 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +    return console.log(result);
return array from function, and think about an easier copy of array

2019-11-06 22:20 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +    return console.log(result);
return result of indexOf

2019-11-06 22:20 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +    return console.log(result);
return result from func

2019-11-09 19:29 UTC, Mike-Savin approved these changes
👍

2019-11-10 15:09 UTC, merged